### ISSUE TITLE
Сохранения хэша пароля, а не самого пароля

### ISSUE THREAD

**Issue by ibmiigaik** [ibmiigaik/session_service#3]
Переделать процесс регистрации пользователя так, чтобы в БД хранился не пароль, а его хэш. Соответственно, при аутентификации пользователя, сверять хэш переданного пароля с хэшем в БД

**Comment by SergMach** [comment]
Я возьму (Мачулко Сергей)

**Comment by ibmiigaik** [comment]
Принято
